/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AulasRouteImport } from './routes/aulas'
import { Route as ComecarRouteImport } from './routes/comecar'
import { Route as ConversarRouteImport } from './routes/conversar'
import { Route as NivelamentoRouteImport } from './routes/nivelamento'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PronunciaRouteImport } from './routes/pronuncia'
import { Route as VocabularioRouteImport } from './routes/vocabulario'
import { Route as AulaLessonIdRouteImport } from './routes/aula.$lessonId'
import { Route as ApiPublicTranscribeRouteImport } from './routes/api/public/transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasRoute = AulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComecarRoute = ComecarRouteImport.update({
  id: '/comecar',
  path: '/comecar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversarRoute = ConversarRouteImport.update({
  id: '/conversar',
  path: '/conversar',
  getParentRoute: () => rootRouteImport,
} as any)
const NivelamentoRoute = NivelamentoRouteImport.update({
  id: '/nivelamento',
  path: '/nivelamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PronunciaRoute = PronunciaRouteImport.update({
  id: '/pronuncia',
  path: '/pronuncia',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularioRoute = VocabularioRouteImport.update({
  id: '/vocabulario',
  path: '/vocabulario',
  getParentRoute: () => rootRouteImport,
} as any)
const AulaLessonIdRoute = AulaLessonIdRouteImport.update({
  id: '/aula/$lessonId',
  path: '/aula/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranscribeRoute = ApiPublicTranscribeRouteImport.update({
  id: '/api/public/transcribe',
  path: '/api/public/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aulas': typeof AulasRoute
  '/comecar': typeof ComecarRoute
  '/conversar': typeof ConversarRoute
  '/nivelamento': typeof NivelamentoRoute
  '/perfil': typeof PerfilRoute
  '/pronuncia': typeof PronunciaRoute
  '/vocabulario': typeof VocabularioRoute
  '/aula/$lessonId': typeof AulaLessonIdRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aulas': typeof AulasRoute
  '/comecar': typeof ComecarRoute
  '/conversar': typeof ConversarRoute
  '/nivelamento': typeof NivelamentoRoute
  '/perfil': typeof PerfilRoute
  '/pronuncia': typeof PronunciaRoute
  '/vocabulario': typeof VocabularioRoute
  '/aula/$lessonId': typeof AulaLessonIdRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aulas': typeof AulasRoute
  '/comecar': typeof ComecarRoute
  '/conversar': typeof ConversarRoute
  '/nivelamento': typeof NivelamentoRoute
  '/perfil': typeof PerfilRoute
  '/pronuncia': typeof PronunciaRoute
  '/vocabulario': typeof VocabularioRoute
  '/aula/$lessonId': typeof AulaLessonIdRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aulas'
    | '/comecar'
    | '/conversar'
    | '/nivelamento'
    | '/perfil'
    | '/pronuncia'
    | '/vocabulario'
    | '/aula/$lessonId'
    | '/api/public/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aulas'
    | '/comecar'
    | '/conversar'
    | '/nivelamento'
    | '/perfil'
    | '/pronuncia'
    | '/vocabulario'
    | '/aula/$lessonId'
    | '/api/public/transcribe'
  id:
    | '__root__'
    | '/'
    | '/aulas'
    | '/comecar'
    | '/conversar'
    | '/nivelamento'
    | '/perfil'
    | '/pronuncia'
    | '/vocabulario'
    | '/aula/$lessonId'
    | '/api/public/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AulasRoute: typeof AulasRoute
  ComecarRoute: typeof ComecarRoute
  ConversarRoute: typeof ConversarRoute
  NivelamentoRoute: typeof NivelamentoRoute
  PerfilRoute: typeof PerfilRoute
  PronunciaRoute: typeof PronunciaRoute
  VocabularioRoute: typeof VocabularioRoute
  AulaLessonIdRoute: typeof AulaLessonIdRoute
  ApiPublicTranscribeRoute: typeof ApiPublicTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas': {
      id: '/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comecar': {
      id: '/comecar'
      path: '/comecar'
      fullPath: '/comecar'
      preLoaderRoute: typeof ComecarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversar': {
      id: '/conversar'
      path: '/conversar'
      fullPath: '/conversar'
      preLoaderRoute: typeof ConversarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nivelamento': {
      id: '/nivelamento'
      path: '/nivelamento'
      fullPath: '/nivelamento'
      preLoaderRoute: typeof NivelamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronuncia': {
      id: '/pronuncia'
      path: '/pronuncia'
      fullPath: '/pronuncia'
      preLoaderRoute: typeof PronunciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulario': {
      id: '/vocabulario'
      path: '/vocabulario'
      fullPath: '/vocabulario'
      preLoaderRoute: typeof VocabularioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula/$lessonId': {
      id: '/aula/$lessonId'
      path: '/aula/$lessonId'
      fullPath: '/aula/$lessonId'
      preLoaderRoute: typeof AulaLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transcribe': {
      id: '/api/public/transcribe'
      path: '/api/public/transcribe'
      fullPath: '/api/public/transcribe'
      preLoaderRoute: typeof ApiPublicTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AulasRoute: AulasRoute,
  ComecarRoute: ComecarRoute,
  ConversarRoute: ConversarRoute,
  NivelamentoRoute: NivelamentoRoute,
  PerfilRoute: PerfilRoute,
  PronunciaRoute: PronunciaRoute,
  VocabularioRoute: VocabularioRoute,
  AulaLessonIdRoute: AulaLessonIdRoute,
  ApiPublicTranscribeRoute: ApiPublicTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
