/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AulasRouteImport } from './routes/aulas'
import { Route as CertificadosRouteImport } from './routes/certificados'
import { Route as ComecarRouteImport } from './routes/comecar'
import { Route as ConquistasRouteImport } from './routes/conquistas'
import { Route as ConversarRouteImport } from './routes/conversar'
import { Route as DicionarioRouteImport } from './routes/dicionario'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as ExerciciosRouteImport } from './routes/exercicios'
import { Route as GramaticaRouteImport } from './routes/gramatica'
import { Route as LembretesRouteImport } from './routes/lembretes'
import { Route as NivelamentoRouteImport } from './routes/nivelamento'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as ProfessorRouteImport } from './routes/professor'
import { Route as ProfissionalRouteImport } from './routes/profissional'
import { Route as PronunciaRouteImport } from './routes/pronuncia'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as RevisaoRouteImport } from './routes/revisao'
import { Route as ValidarRouteImport } from './routes/validar'
import { Route as ViagensRouteImport } from './routes/viagens'
import { Route as VocabularioRouteImport } from './routes/vocabulario'
import { Route as AulaLessonIdRouteImport } from './routes/aula.$lessonId'
import { Route as ApiPublicTranscribeRouteImport } from './routes/api/public/transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasRoute = AulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadosRoute = CertificadosRouteImport.update({
  id: '/certificados',
  path: '/certificados',
  getParentRoute: () => rootRouteImport,
} as any)
const ComecarRoute = ComecarRouteImport.update({
  id: '/comecar',
  path: '/comecar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquistasRoute = ConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversarRoute = ConversarRouteImport.update({
  id: '/conversar',
  path: '/conversar',
  getParentRoute: () => rootRouteImport,
} as any)
const DicionarioRoute = DicionarioRouteImport.update({
  id: '/dicionario',
  path: '/dicionario',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciciosRoute = ExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const GramaticaRoute = GramaticaRouteImport.update({
  id: '/gramatica',
  path: '/gramatica',
  getParentRoute: () => rootRouteImport,
} as any)
const LembretesRoute = LembretesRouteImport.update({
  id: '/lembretes',
  path: '/lembretes',
  getParentRoute: () => rootRouteImport,
} as any)
const NivelamentoRoute = NivelamentoRouteImport.update({
  id: '/nivelamento',
  path: '/nivelamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorRoute = ProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionalRoute = ProfissionalRouteImport.update({
  id: '/profissional',
  path: '/profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const PronunciaRoute = PronunciaRouteImport.update({
  id: '/pronuncia',
  path: '/pronuncia',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisaoRoute = RevisaoRouteImport.update({
  id: '/revisao',
  path: '/revisao',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidarRoute = ValidarRouteImport.update({
  id: '/validar',
  path: '/validar',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagensRoute = ViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularioRoute = VocabularioRouteImport.update({
  id: '/vocabulario',
  path: '/vocabulario',
  getParentRoute: () => rootRouteImport,
} as any)
const AulaLessonIdRoute = AulaLessonIdRouteImport.update({
  id: '/aula/$lessonId',
  path: '/aula/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranscribeRoute = ApiPublicTranscribeRouteImport.update({
  id: '/api/public/transcribe',
  path: '/api/public/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aulas': typeof AulasRoute
  '/certificados': typeof CertificadosRoute
  '/comecar': typeof ComecarRoute
  '/conquistas': typeof ConquistasRoute
  '/conversar': typeof ConversarRoute
  '/dicionario': typeof DicionarioRoute
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/exercicios': typeof ExerciciosRoute
  '/gramatica': typeof GramaticaRoute
  '/lembretes': typeof LembretesRoute
  '/nivelamento': typeof NivelamentoRoute
  '/perfil': typeof PerfilRoute
  '/plano': typeof PlanoRoute
  '/premium': typeof PremiumRoute
  '/professor': typeof ProfessorRoute
  '/profissional': typeof ProfissionalRoute
  '/pronuncia': typeof PronunciaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorio': typeof RelatorioRoute
  '/revisao': typeof RevisaoRoute
  '/validar': typeof ValidarRoute
  '/viagens': typeof ViagensRoute
  '/vocabulario': typeof VocabularioRoute
  '/aula/$lessonId': typeof AulaLessonIdRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aulas': typeof AulasRoute
  '/certificados': typeof CertificadosRoute
  '/comecar': typeof ComecarRoute
  '/conquistas': typeof ConquistasRoute
  '/conversar': typeof ConversarRoute
  '/dicionario': typeof DicionarioRoute
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/exercicios': typeof ExerciciosRoute
  '/gramatica': typeof GramaticaRoute
  '/lembretes': typeof LembretesRoute
  '/nivelamento': typeof NivelamentoRoute
  '/perfil': typeof PerfilRoute
  '/plano': typeof PlanoRoute
  '/premium': typeof PremiumRoute
  '/professor': typeof ProfessorRoute
  '/profissional': typeof ProfissionalRoute
  '/pronuncia': typeof PronunciaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorio': typeof RelatorioRoute
  '/revisao': typeof RevisaoRoute
  '/validar': typeof ValidarRoute
  '/viagens': typeof ViagensRoute
  '/vocabulario': typeof VocabularioRoute
  '/aula/$lessonId': typeof AulaLessonIdRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aulas': typeof AulasRoute
  '/certificados': typeof CertificadosRoute
  '/comecar': typeof ComecarRoute
  '/conquistas': typeof ConquistasRoute
  '/conversar': typeof ConversarRoute
  '/dicionario': typeof DicionarioRoute
  '/entrar': typeof EntrarRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/exercicios': typeof ExerciciosRoute
  '/gramatica': typeof GramaticaRoute
  '/lembretes': typeof LembretesRoute
  '/nivelamento': typeof NivelamentoRoute
  '/perfil': typeof PerfilRoute
  '/plano': typeof PlanoRoute
  '/premium': typeof PremiumRoute
  '/professor': typeof ProfessorRoute
  '/profissional': typeof ProfissionalRoute
  '/pronuncia': typeof PronunciaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/relatorio': typeof RelatorioRoute
  '/revisao': typeof RevisaoRoute
  '/validar': typeof ValidarRoute
  '/viagens': typeof ViagensRoute
  '/vocabulario': typeof VocabularioRoute
  '/aula/$lessonId': typeof AulaLessonIdRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aulas'
    | '/certificados'
    | '/comecar'
    | '/conquistas'
    | '/conversar'
    | '/dicionario'
    | '/entrar'
    | '/esqueci-senha'
    | '/exercicios'
    | '/gramatica'
    | '/lembretes'
    | '/nivelamento'
    | '/perfil'
    | '/plano'
    | '/premium'
    | '/professor'
    | '/profissional'
    | '/pronuncia'
    | '/redefinir-senha'
    | '/relatorio'
    | '/revisao'
    | '/validar'
    | '/viagens'
    | '/vocabulario'
    | '/aula/$lessonId'
    | '/api/public/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aulas'
    | '/certificados'
    | '/comecar'
    | '/conquistas'
    | '/conversar'
    | '/dicionario'
    | '/entrar'
    | '/esqueci-senha'
    | '/exercicios'
    | '/gramatica'
    | '/lembretes'
    | '/nivelamento'
    | '/perfil'
    | '/plano'
    | '/premium'
    | '/professor'
    | '/profissional'
    | '/pronuncia'
    | '/redefinir-senha'
    | '/relatorio'
    | '/revisao'
    | '/validar'
    | '/viagens'
    | '/vocabulario'
    | '/aula/$lessonId'
    | '/api/public/transcribe'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aulas'
    | '/certificados'
    | '/comecar'
    | '/conquistas'
    | '/conversar'
    | '/dicionario'
    | '/entrar'
    | '/esqueci-senha'
    | '/exercicios'
    | '/gramatica'
    | '/lembretes'
    | '/nivelamento'
    | '/perfil'
    | '/plano'
    | '/premium'
    | '/professor'
    | '/profissional'
    | '/pronuncia'
    | '/redefinir-senha'
    | '/relatorio'
    | '/revisao'
    | '/validar'
    | '/viagens'
    | '/vocabulario'
    | '/aula/$lessonId'
    | '/api/public/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AulasRoute: typeof AulasRoute
  CertificadosRoute: typeof CertificadosRoute
  ComecarRoute: typeof ComecarRoute
  ConquistasRoute: typeof ConquistasRoute
  ConversarRoute: typeof ConversarRoute
  DicionarioRoute: typeof DicionarioRoute
  EntrarRoute: typeof EntrarRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  ExerciciosRoute: typeof ExerciciosRoute
  GramaticaRoute: typeof GramaticaRoute
  LembretesRoute: typeof LembretesRoute
  NivelamentoRoute: typeof NivelamentoRoute
  PerfilRoute: typeof PerfilRoute
  PlanoRoute: typeof PlanoRoute
  PremiumRoute: typeof PremiumRoute
  ProfessorRoute: typeof ProfessorRoute
  ProfissionalRoute: typeof ProfissionalRoute
  PronunciaRoute: typeof PronunciaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RelatorioRoute: typeof RelatorioRoute
  RevisaoRoute: typeof RevisaoRoute
  ValidarRoute: typeof ValidarRoute
  ViagensRoute: typeof ViagensRoute
  VocabularioRoute: typeof VocabularioRoute
  AulaLessonIdRoute: typeof AulaLessonIdRoute
  ApiPublicTranscribeRoute: typeof ApiPublicTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas': {
      id: '/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificados': {
      id: '/certificados'
      path: '/certificados'
      fullPath: '/certificados'
      preLoaderRoute: typeof CertificadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comecar': {
      id: '/comecar'
      path: '/comecar'
      fullPath: '/comecar'
      preLoaderRoute: typeof ComecarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquistas': {
      id: '/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof ConquistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversar': {
      id: '/conversar'
      path: '/conversar'
      fullPath: '/conversar'
      preLoaderRoute: typeof ConversarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dicionario': {
      id: '/dicionario'
      path: '/dicionario'
      fullPath: '/dicionario'
      preLoaderRoute: typeof DicionarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicios': {
      id: '/exercicios'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof ExerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gramatica': {
      id: '/gramatica'
      path: '/gramatica'
      fullPath: '/gramatica'
      preLoaderRoute: typeof GramaticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lembretes': {
      id: '/lembretes'
      path: '/lembretes'
      fullPath: '/lembretes'
      preLoaderRoute: typeof LembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nivelamento': {
      id: '/nivelamento'
      path: '/nivelamento'
      fullPath: '/nivelamento'
      preLoaderRoute: typeof NivelamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor': {
      id: '/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof ProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissional': {
      id: '/profissional'
      path: '/profissional'
      fullPath: '/profissional'
      preLoaderRoute: typeof ProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronuncia': {
      id: '/pronuncia'
      path: '/pronuncia'
      fullPath: '/pronuncia'
      preLoaderRoute: typeof PronunciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisao': {
      id: '/revisao'
      path: '/revisao'
      fullPath: '/revisao'
      preLoaderRoute: typeof RevisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validar': {
      id: '/validar'
      path: '/validar'
      fullPath: '/validar'
      preLoaderRoute: typeof ValidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagens': {
      id: '/viagens'
      path: '/viagens'
      fullPath: '/viagens'
      preLoaderRoute: typeof ViagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulario': {
      id: '/vocabulario'
      path: '/vocabulario'
      fullPath: '/vocabulario'
      preLoaderRoute: typeof VocabularioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula/$lessonId': {
      id: '/aula/$lessonId'
      path: '/aula/$lessonId'
      fullPath: '/aula/$lessonId'
      preLoaderRoute: typeof AulaLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transcribe': {
      id: '/api/public/transcribe'
      path: '/api/public/transcribe'
      fullPath: '/api/public/transcribe'
      preLoaderRoute: typeof ApiPublicTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AulasRoute: AulasRoute,
  CertificadosRoute: CertificadosRoute,
  ComecarRoute: ComecarRoute,
  ConquistasRoute: ConquistasRoute,
  ConversarRoute: ConversarRoute,
  DicionarioRoute: DicionarioRoute,
  EntrarRoute: EntrarRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  ExerciciosRoute: ExerciciosRoute,
  GramaticaRoute: GramaticaRoute,
  LembretesRoute: LembretesRoute,
  NivelamentoRoute: NivelamentoRoute,
  PerfilRoute: PerfilRoute,
  PlanoRoute: PlanoRoute,
  PremiumRoute: PremiumRoute,
  ProfessorRoute: ProfessorRoute,
  ProfissionalRoute: ProfissionalRoute,
  PronunciaRoute: PronunciaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RelatorioRoute: RelatorioRoute,
  RevisaoRoute: RevisaoRoute,
  ValidarRoute: ValidarRoute,
  ViagensRoute: ViagensRoute,
  VocabularioRoute: VocabularioRoute,
  AulaLessonIdRoute: AulaLessonIdRoute,
  ApiPublicTranscribeRoute: ApiPublicTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
