/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AulasRouteImport } from './routes/aulas'
import { Route as ComecarRouteImport } from './routes/comecar'
import { Route as ConquistasRouteImport } from './routes/conquistas'
import { Route as ConversarRouteImport } from './routes/conversar'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ExerciciosRouteImport } from './routes/exercicios'
import { Route as GramaticaRouteImport } from './routes/gramatica'
import { Route as NivelamentoRouteImport } from './routes/nivelamento'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ProfissionalRouteImport } from './routes/profissional'
import { Route as PronunciaRouteImport } from './routes/pronuncia'
import { Route as RevisaoRouteImport } from './routes/revisao'
import { Route as ViagensRouteImport } from './routes/viagens'
import { Route as VocabularioRouteImport } from './routes/vocabulario'
import { Route as AulaLessonIdRouteImport } from './routes/aula.$lessonId'
import { Route as ApiPublicTranscribeRouteImport } from './routes/api/public/transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasRoute = AulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComecarRoute = ComecarRouteImport.update({
  id: '/comecar',
  path: '/comecar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquistasRoute = ConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversarRoute = ConversarRouteImport.update({
  id: '/conversar',
  path: '/conversar',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciciosRoute = ExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const GramaticaRoute = GramaticaRouteImport.update({
  id: '/gramatica',
  path: '/gramatica',
  getParentRoute: () => rootRouteImport,
} as any)
const NivelamentoRoute = NivelamentoRouteImport.update({
  id: '/nivelamento',
  path: '/nivelamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionalRoute = ProfissionalRouteImport.update({
  id: '/profissional',
  path: '/profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const PronunciaRoute = PronunciaRouteImport.update({
  id: '/pronuncia',
  path: '/pronuncia',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisaoRoute = RevisaoRouteImport.update({
  id: '/revisao',
  path: '/revisao',
  getParentRoute: () => rootRouteImport,
} as any)
const ViagensRoute = ViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularioRoute = VocabularioRouteImport.update({
  id: '/vocabulario',
  path: '/vocabulario',
  getParentRoute: () => rootRouteImport,
} as any)
const AulaLessonIdRoute = AulaLessonIdRouteImport.update({
  id: '/aula/$lessonId',
  path: '/aula/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTranscribeRoute = ApiPublicTranscribeRouteImport.update({
  id: '/api/public/transcribe',
  path: '/api/public/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aulas': typeof AulasRoute
  '/comecar': typeof ComecarRoute
  '/conquistas': typeof ConquistasRoute
  '/conversar': typeof ConversarRoute
  '/entrar': typeof EntrarRoute
  '/exercicios': typeof ExerciciosRoute
  '/gramatica': typeof GramaticaRoute
  '/nivelamento': typeof NivelamentoRoute
  '/perfil': typeof PerfilRoute
  '/profissional': typeof ProfissionalRoute
  '/pronuncia': typeof PronunciaRoute
  '/revisao': typeof RevisaoRoute
  '/viagens': typeof ViagensRoute
  '/vocabulario': typeof VocabularioRoute
  '/aula/$lessonId': typeof AulaLessonIdRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aulas': typeof AulasRoute
  '/comecar': typeof ComecarRoute
  '/conquistas': typeof ConquistasRoute
  '/conversar': typeof ConversarRoute
  '/entrar': typeof EntrarRoute
  '/exercicios': typeof ExerciciosRoute
  '/gramatica': typeof GramaticaRoute
  '/nivelamento': typeof NivelamentoRoute
  '/perfil': typeof PerfilRoute
  '/profissional': typeof ProfissionalRoute
  '/pronuncia': typeof PronunciaRoute
  '/revisao': typeof RevisaoRoute
  '/viagens': typeof ViagensRoute
  '/vocabulario': typeof VocabularioRoute
  '/aula/$lessonId': typeof AulaLessonIdRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aulas': typeof AulasRoute
  '/comecar': typeof ComecarRoute
  '/conquistas': typeof ConquistasRoute
  '/conversar': typeof ConversarRoute
  '/entrar': typeof EntrarRoute
  '/exercicios': typeof ExerciciosRoute
  '/gramatica': typeof GramaticaRoute
  '/nivelamento': typeof NivelamentoRoute
  '/perfil': typeof PerfilRoute
  '/profissional': typeof ProfissionalRoute
  '/pronuncia': typeof PronunciaRoute
  '/revisao': typeof RevisaoRoute
  '/viagens': typeof ViagensRoute
  '/vocabulario': typeof VocabularioRoute
  '/aula/$lessonId': typeof AulaLessonIdRoute
  '/api/public/transcribe': typeof ApiPublicTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aulas'
    | '/comecar'
    | '/conquistas'
    | '/conversar'
    | '/entrar'
    | '/exercicios'
    | '/gramatica'
    | '/nivelamento'
    | '/perfil'
    | '/profissional'
    | '/pronuncia'
    | '/revisao'
    | '/viagens'
    | '/vocabulario'
    | '/aula/$lessonId'
    | '/api/public/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aulas'
    | '/comecar'
    | '/conquistas'
    | '/conversar'
    | '/entrar'
    | '/exercicios'
    | '/gramatica'
    | '/nivelamento'
    | '/perfil'
    | '/profissional'
    | '/pronuncia'
    | '/revisao'
    | '/viagens'
    | '/vocabulario'
    | '/aula/$lessonId'
    | '/api/public/transcribe'
  id:
    | '__root__'
    | '/'
    | '/aulas'
    | '/comecar'
    | '/conquistas'
    | '/conversar'
    | '/entrar'
    | '/exercicios'
    | '/gramatica'
    | '/nivelamento'
    | '/perfil'
    | '/profissional'
    | '/pronuncia'
    | '/revisao'
    | '/viagens'
    | '/vocabulario'
    | '/aula/$lessonId'
    | '/api/public/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AulasRoute: typeof AulasRoute
  ComecarRoute: typeof ComecarRoute
  ConquistasRoute: typeof ConquistasRoute
  ConversarRoute: typeof ConversarRoute
  EntrarRoute: typeof EntrarRoute
  ExerciciosRoute: typeof ExerciciosRoute
  GramaticaRoute: typeof GramaticaRoute
  NivelamentoRoute: typeof NivelamentoRoute
  PerfilRoute: typeof PerfilRoute
  ProfissionalRoute: typeof ProfissionalRoute
  PronunciaRoute: typeof PronunciaRoute
  RevisaoRoute: typeof RevisaoRoute
  ViagensRoute: typeof ViagensRoute
  VocabularioRoute: typeof VocabularioRoute
  AulaLessonIdRoute: typeof AulaLessonIdRoute
  ApiPublicTranscribeRoute: typeof ApiPublicTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas': {
      id: '/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comecar': {
      id: '/comecar'
      path: '/comecar'
      fullPath: '/comecar'
      preLoaderRoute: typeof ComecarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquistas': {
      id: '/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof ConquistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversar': {
      id: '/conversar'
      path: '/conversar'
      fullPath: '/conversar'
      preLoaderRoute: typeof ConversarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicios': {
      id: '/exercicios'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof ExerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gramatica': {
      id: '/gramatica'
      path: '/gramatica'
      fullPath: '/gramatica'
      preLoaderRoute: typeof GramaticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nivelamento': {
      id: '/nivelamento'
      path: '/nivelamento'
      fullPath: '/nivelamento'
      preLoaderRoute: typeof NivelamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissional': {
      id: '/profissional'
      path: '/profissional'
      fullPath: '/profissional'
      preLoaderRoute: typeof ProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronuncia': {
      id: '/pronuncia'
      path: '/pronuncia'
      fullPath: '/pronuncia'
      preLoaderRoute: typeof PronunciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisao': {
      id: '/revisao'
      path: '/revisao'
      fullPath: '/revisao'
      preLoaderRoute: typeof RevisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viagens': {
      id: '/viagens'
      path: '/viagens'
      fullPath: '/viagens'
      preLoaderRoute: typeof ViagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulario': {
      id: '/vocabulario'
      path: '/vocabulario'
      fullPath: '/vocabulario'
      preLoaderRoute: typeof VocabularioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aula/$lessonId': {
      id: '/aula/$lessonId'
      path: '/aula/$lessonId'
      fullPath: '/aula/$lessonId'
      preLoaderRoute: typeof AulaLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/transcribe': {
      id: '/api/public/transcribe'
      path: '/api/public/transcribe'
      fullPath: '/api/public/transcribe'
      preLoaderRoute: typeof ApiPublicTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AulasRoute: AulasRoute,
  ComecarRoute: ComecarRoute,
  ConquistasRoute: ConquistasRoute,
  ConversarRoute: ConversarRoute,
  EntrarRoute: EntrarRoute,
  ExerciciosRoute: ExerciciosRoute,
  GramaticaRoute: GramaticaRoute,
  NivelamentoRoute: NivelamentoRoute,
  PerfilRoute: PerfilRoute,
  ProfissionalRoute: ProfissionalRoute,
  PronunciaRoute: PronunciaRoute,
  RevisaoRoute: RevisaoRoute,
  ViagensRoute: ViagensRoute,
  VocabularioRoute: VocabularioRoute,
  AulaLessonIdRoute: AulaLessonIdRoute,
  ApiPublicTranscribeRoute: ApiPublicTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
